// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw68BCyu8qL8S7hEpvvitx0RDG6d6q_18',
    appId: '1:747918394033:web:72b9fe8a66a62d02141890',
    messagingSenderId: '747918394033',
    projectId: 'bitedrop-2435d',
    authDomain: 'bitedrop-2435d.firebaseapp.com',
    storageBucket: 'bitedrop-2435d.firebasestorage.app',
    measurementId: 'G-QVYPGQYTQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3rGHmjUynPDGYzGSNVw_1IWHeNq-fwo',
    appId: '1:747918394033:android:340ed0aaded57a4b141890',
    messagingSenderId: '747918394033',
    projectId: 'bitedrop-2435d',
    storageBucket: 'bitedrop-2435d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRNF5BTkN3Jq6d05H55WKfRycFwPM-9O8',
    appId: '1:747918394033:ios:1c09e70ad7fe54e7141890',
    messagingSenderId: '747918394033',
    projectId: 'bitedrop-2435d',
    storageBucket: 'bitedrop-2435d.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRNF5BTkN3Jq6d05H55WKfRycFwPM-9O8',
    appId: '1:747918394033:ios:1c09e70ad7fe54e7141890',
    messagingSenderId: '747918394033',
    projectId: 'bitedrop-2435d',
    storageBucket: 'bitedrop-2435d.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw68BCyu8qL8S7hEpvvitx0RDG6d6q_18',
    appId: '1:747918394033:web:b83a951bd40df80e141890',
    messagingSenderId: '747918394033',
    projectId: 'bitedrop-2435d',
    authDomain: 'bitedrop-2435d.firebaseapp.com',
    storageBucket: 'bitedrop-2435d.firebasestorage.app',
    measurementId: 'G-B51RLVWQ99',
  );
}

